apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 8081
  - name: webwatcher
    image: afakharany/watcher:latest