apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: helloworld-controller
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:        
      containers:
      - name: k8-demo
        image: jayesh07docker/jayesh-repo
        ports:
        - name: nodejs-port
          containerPort: 8080